baseURL = "https://spaceincode.github.io/"
languageCode = "en-us"

title = "Wang Jinghui"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 5 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
canonifyurls = true
publishDir = "docs"
contentdir = "content"
layoutdir = "layouts"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""
hasCJKLanguage = true

[taxonomies]
  category = "categories"
  tag = "tags"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
    math = true
    # Blog description at the top of the homepage. Supports markdown.
    description = "Idea, Creation and Self-development"
    author = "Wang Jinghui"
    showReadMore = false
   
    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

    # Add links to your accounts. Remove the ones you don't want to include.
    # Main
    email = "2507558818@qq.com"
    #facebook = "#"
    #twitter = "#"
    #instagram = "#"
    #tumblr = "#"
    #reddit = "#"
    #pinterest = "#"
    #youtube = "#"
    #vimeo = "#"
    #weibo = "#"
    #vk = "#"
    #linkedin = "#"

    # Programming
    github = "https://github.com/SpaceInCode"
    #stackoverflow = "#"
    #gitlab = "#"
    #codepen = "#"

    # Academic
    #googlescholar = "#"
    #impactstory = "#"
    #orcid = "#"

    # Travel
    #googlemaps = "#"
    #tripadvisor = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3



